name: Terraform Auto Deploy

on:
  push:
    branches: [main]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Terraform Action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.tf_action == 'plan'
        run: terraform plan -var-file="variables.tfvars" -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.tf_action == 'apply'
        run: terraform apply -input=false tfplan

      - name: Terraform Destroy
        if: github.event.inputs.tf_action == 'destroy'
        run: terraform destroy -auto-approve -var-file="variables.tfvars"
